spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3307/cloud_native_batch?useUnicode=true&characterEncoding=utf8
      username: '{cipher}b87ab015de7fa77bc9559d8fdc8b996f54d8356e5670054bc694208ede055fa8'
      password: '{cipher}4393d942318ca50d4f5fa9417021fa8f50d64d126dc252e927c38e9fad57aa62'
      driver-class-name: org.mariadb.jdbc.Driver
cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    region:
    static:
    auto:

job:
  resource-path: s3://spring-native-batch/inputs/*.csv